spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org:
      hibernate:
        type: trace

server:
  port: 8098

graphql:
  servlet:
    mapping: /api/graphql
    enabled: true
    corsEnabled: true
